In [9]:
import tensorflow as tf
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import f1_score, precision_score, recall_score

In [10]:
test_data = tf.keras.utils.image_dataset_from_directory(
    "./data/test",
    image_size=(224, 224),
    batch_size=32
)

Found 2201 files belonging to 7 classes.


In [13]:
model_path = "../model/v10_model_best.keras"

In [14]:
model = tf.keras.models.load_model(model_path)

In [15]:
# Evaluate the model
test_loss, test_accuracy = model.evaluate(test_data)
print(f"Test Loss: {test_loss}")
print(f"Test Accuracy: {test_accuracy}")

69/69 ━━━━━━━━━━━━━━━━━━━━ 43s 591ms/step - accuracy: 0.6179 - loss: 1.4621
Test Loss: 1.4938055276870728
Test Accuracy: 0.6115401983261108


In [16]:

# Make predictions for detailed analysis
y_true = []  # Ground truth labels
y_pred = []  # Predicted labels

for images, labels in test_data:
    predictions = model.predict(images)
    y_true.extend(labels.numpy())
    y_pred.extend(tf.argmax(predictions, axis=1).numpy())

1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 612ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 624ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 615ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 602ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 605ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 631ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 619ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 622ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 623ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 625ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 609ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 602ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 615ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 605ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 619ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 607ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 600ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 605ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 626ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 614ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 605ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 610ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 609ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 607ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 

In [18]:
print("Classification Report:")
print(classification_report(y_true, y_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_true, y_pred))

print(f"Precision (weighted): {precision_score(y_true, y_pred, average='weighted')}")
print(f"Recall (weighted): {recall_score(y_true, y_pred, average='weighted')}")
print(f"F1 Score (weighted): {f1_score(y_true, y_pred, average='weighted')}")

Classification Report:
              precision    recall  f1-score   support

           0       0.80      0.80      0.80       312
           1       0.56      0.67      0.61       288
           2       0.63      0.57      0.60       309
           3       0.51      0.54      0.52       352
           4       0.66      0.55      0.60       343
           5       0.53      0.62      0.58       325
           6       0.64      0.53      0.58       272

    accuracy                           0.61      2201
   macro avg       0.62      0.61      0.61      2201
weighted avg       0.62      0.61      0.61      2201

Confusion Matrix:
[[251  13   2  14   7  17   8]
 [  8 194  13  30  22  16   5]
 [  3  22 176  49   7  44   8]
 [  6  26  31 189  21  57  22]
 [ 13  53  15  33 188  21  20]
 [ 14  14  24  39  14 203  17]
 [ 20  25  17  17  26  22 145]]
Precision (weighted): 0.6177817110828305
Recall (weighted): 0.611540208995911
F1 Score (weighted): 0.6116947804072387
